# Fly.io Configuration for CeialMilk
app = "ceialmilk"
primary_region = "gru"  # São Paulo, Brazil

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  JAVA_OPTS = "-Xmx512m -Xms256m"
  SERVER_PORT = "8080"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/java"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    method = "GET"
    path = "/actuator/health"
    protocol = "http"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Configurações de escalabilidade
[scale]
  memory = "512mb"
  vm_size = "shared-cpu-1x"

# Configurações de deploy
[deploy]
  strategy = "rolling"
  release_command = "echo 'Release completed'"
