spring:
  application:
    name: ceialmilk
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://${DB_HOST:ceialmilk-db}:${DB_PORT:5432}/${DB_NAME:ceialmilk}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:ceialmilk-db}:${DB_PORT:5432}/${DB_NAME:ceialmilk}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

logging:
  level:
    com.ceialmilk: DEBUG
    org.springframework.security: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ceialmilk-super-secret-key-2024-spring-webflux-reactive-jwt
  expiration: 86400
