-- Row Level Security: satisfies PostgREST/Supabase-style linters for tables in public.
-- No policies: anon/authenticated (PostgREST) see no rows; backend uses DATABASE_URL role
-- that owns tables and bypasses RLS by default (PostgreSQL table owner behavior).

ALTER TABLE analises_solo ENABLE ROW LEVEL SECURITY;
ALTER TABLE animais ENABLE ROW LEVEL SECURITY;
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE cios ENABLE ROW LEVEL SECURITY;
ALTER TABLE coberturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE crias ENABLE ROW LEVEL SECURITY;
ALTER TABLE custos_agricolas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dev_studio_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE dev_studio_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE diagnosticos_gestacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE escala_folgas ENABLE ROW LEVEL SECURITY;
ALTER TABLE fazendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE folgas_alteracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE folgas_escala_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE folgas_excecoes_dia ENABLE ROW LEVEL SECURITY;
ALTER TABLE folgas_justificativas ENABLE ROW LEVEL SECURITY;
ALTER TABLE fornecedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE gestacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE lactacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE lotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes_lote ENABLE ROW LEVEL SECURITY;
ALTER TABLE partos ENABLE ROW LEVEL SECURITY;
ALTER TABLE producao_leite ENABLE ROW LEVEL SECURITY;
ALTER TABLE producoes_agricolas ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocolos_iatf ENABLE ROW LEVEL SECURITY;
ALTER TABLE receitas_agricolas ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE safras_culturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE secagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios_fazendas ENABLE ROW LEVEL SECURITY;
