DELETE FROM alertas WHERE tipo IN ('HORMONIO_LACTACAO_PENDENTE');

ALTER TABLE alertas DROP CONSTRAINT IF EXISTS alertas_tipo_check;
ALTER TABLE alertas ADD CONSTRAINT alertas_tipo_check CHECK (tipo IN (
    'TRATAMENTO_VENCIDO',
    'PARTO_PREVISTO',
    'RESTRICAO_LEITE_ATIVA',
    'NAO_CONFORMIDADE',
    'GESTACAO_SEM_SECAGEM',
    'CIO_DETECTADO',
    'VACINA_VENCIDA',
    'VACINA_REFORCO_VENCIDA',
    'MANUAL'
));
